#**Working with JSON**

In [1]:
import pandas as pd

In [2]:
pd.read_json('/content/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.0384
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.6870
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.8570
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,3.8400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.1730
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.1980
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-01,1785542401,0.2790

#**Working with SQL**

In [ ]:
# download xampp- start apcahe and sql, create a new db with ur file name, import the db file u have

In [4]:
#install mysql connector- bridge between mysql and python
!pip install mysql-connector

Collecting mysql-connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 84.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql-connector
  Building wheel for mysql-connector (setup.py) ... done
  Created wheel for mysql-connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=4675b0ec6074d47e27d7e656cfa75be72b937ee2d7e253a7c013530785d06047
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql-connector
Installing collected packages: mysql-connector
Successfully installed mysql-connector-2.2.9

In [5]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='db_name')
pd.read_sql_query('pass the query here',conn)

#**Working with APIs** (Application programming interface)

APIs are nothing but data pipelines which apis the information from one point to another

eg: MakeMyTrip uses API of IRCTC due to which, if we book anything unsing MMT it reflects back to the server of IRCTC

tmdb website- the movies database
google: tmdb api

```
themoviesdb.org
      |
      v
create account
      |
      V
go to settings
      |
      V
     API
      |
      V
API key is there
```

In [ ]:
import pandas as pd
import requests

In [ ]:
response = requests.get('pass the api url')

In [ ]:
response.json() #explicit conversion of data into json format
response.json()['col_name']

In [ ]:
df = pd.DataFrame(response.json()['col_name'])['col_1','col_2','col_3']
#create data frame from the response generated

In [ ]:
df = pd.DataFrame()
for i in range(1,total_pages):
  response = requests.get('pass the api url'+str(i))
  temp_df = pd.DataFrame(response.json()['results'])
  df = pd.concat([df,temp_df],ignore_index=True)

In [ ]:
# conver the response to csv
df.to_csv('filename.csv')

rapidapi - list of all free apis